### PR TITLE
add http2 for upstream support

### PR DESCRIPTION
**Pull request by hishamanver**
This PR adds support for http2 upstream servers

### CODE REVIEW

**Comment by hishamanver** [comment]
This links to https://github.com/rpardini/docker-registry-proxy/issues/101

**Comment by hishamanver** [comment]
@rpardini any comments for this one?

**Comment by rpardini** [comment]
Yeah, this is not real http2 support, since nginx itself does not support it.

**Comment by hishamanver** [comment]
ok let me clarify

this PR forces all connections between the d-r-p and the upstream to use http 1.1 even when the upstream wants to use http2

If this is not done, the client connecting to the proxy receives a HTTP 426 error

**Comment by hishamanver** [comment]
@rpardini does this make sense?

**Comment by rpardini** [comment]
Hi, I've personally not received 426 from upstream registries. Dunno what's up there. 
I know nginx can only talk 1.1 to upstreams, the Upgrade/Connection hack is the same as for websockets.
What is the connection being upgraded to?

**Comment by rpardini** [comment]
I can see the value in this, but it can't be the default behaviour. Please hide it with an ENV check and include file.

**Comment by hishamanver** [comment]
done, please see https://github.com/rpardini/docker-registry-proxy/pull/128

**Pull request closed without merging**
