### PR TITLE
DRP-70: add timeoutes as ENVs, update README.md, update nginx config, update in advance docker version

### PR DESCRIPTION
**Pull request by SezBulent**

### CODE REVIEW

**Comment by rpardini** [comment]
Merged. Let it build and I will tag it...

**Comment by SezBulent** [comment]
Thank you! I think it's a good idea if the docker hub readme would be updated too.

**Comment by rpardini** [comment]
Hi, no idea how to do that?

**Comment by SezBulent** [comment]
Hm, well if you have a pipeline from github to docker hub, then it should pick up README.md automatically, but if you push the image manually, then i guess you must edit it from the docker hub page.

**Comment by rpardini** [comment]
Yeah, Github Actions deploys to DockerHub and Github Packages... you can find it in .github

**Comment by SezBulent** [comment]
I saw that one, but i was referring to something like this:
.
https://docs.docker.com/docker-hub/builds/#understand-the-build-process

Otherwise, you have to update the dockerhub image README manually, as the current one is for version 0.3.0

**Pull request merged**
